"""Generation of function calls with constrained decoding.

For every test prompt the JSON answer is built piece by piece:

    {"name": "<function>", "parameters": {"<p1>": <v1>, ...}}

The fixed parts (keys, quotes, commas, braces) are written by us with
_append_tokens. The variable parts (function name and each value) are
generated by the model one token at a time, but only among the tokens
that the validators in constrained_decoding.py allow. This guarantees
valid JSON that matches the schema of the chosen function.
"""

import numpy
import json
import sys
from typing import Any
from llm_sdk import Small_LLM_Model
from functools import partial
from .models import TestPrompt, FunctionDefinition, FunctionCallResult
from .constrained_decoding import (invert_vocab, get_valid_function_names,
                                   count_matching_prefixes,
                                   is_valid_number_char,
                                   is_valid_string, is_valid_prefix,
                                   mask_logits, select_valid_token)


def build_prompt(functions: list[FunctionDefinition], prompt: str) -> str:
    """Builds the chat prompt for the model (ChatML format of Qwen).

    The system message holds the instructions and the function
    definitions as indented JSON.
    The user message is the request, and the prompt ends with the
    assistant tag so the model continues from there. The prompt only
    guides the choice: the output structure is enforced by the
    constrained decoding, not by the prompt.

    Args:
        functions: Available function definitions.
        prompt: Natural-language request.

    Returns:
        The full prompt text.
    """

    functions_dict = []
    for f in functions:
        functions_dict.append(f.model_dump())
    functions_text = json.dumps(functions_dict, indent=2)
    instructions = ("Given the following functions, respond with the name of "
                    "the function to call and its parameters, in JSON format. "
                    "Choose the function whose description best matches the "
                    "user's overall intent, not just individual words in the "
                    "prompt. Prioritize \\\\ over other escape chars.")
    result = (
        f"<|im_start|>system\n{instructions}\n\n{functions_text}<|im_end|>\n"
        f"<|im_start|>user\n{prompt}<|im_end|>\n"
        f"<|im_start|>assistant\n"
    )
    return result


def build_error_result(prompt: str, warning: str) -> dict[str, Any]:
    """Prints a warning and builds the ERROR entry for a failed prompt.

    The entry keeps one output item per input prompt, with name
    "ERROR" and empty parameters.

    Args:
        prompt: The original request.
        warning: Message printed to stderr.

    Returns:
        Dict with keys prompt, name and parameters.
    """

    print(f"Warning: {warning}", file=sys.stderr)
    result = FunctionCallResult(prompt=prompt, name="ERROR", parameters={})
    return result.model_dump()


def _append_tokens(model: Small_LLM_Model, token_ids: list[int],
                   text_to_encode: str) -> None:
    """Encodes text and appends its tokens to token_ids.

    Used for the fixed parts of the JSON. These tokens are not chosen
    by the model, they are forced.

    Args:
        model: Model used for its tokenizer.
        token_ids: Token ids of the prompt and of everything forced or
            generated so far. It is modified.
        text_to_encode: Text to encode and append.
    """

    encoded_token_ids = model.encode(text_to_encode)[0].tolist()
    token_ids.extend(encoded_token_ids)


def _generate_function_name(model: Small_LLM_Model, token_ids: list[int],
                            id_to_token: dict[int, str],
                            valid_names: list[str]) -> str:
    """Lets the model choose the function name, token by token.

    At each step only tokens that keep the text as a prefix of a valid
    name are allowed. It stops when the decoded text equals a name and
    no other name starts with it. The chosen tokens are appended to
    token_ids; the closing quote is not.
    If the text is already a complete name that is also a prefix of
    another one, the model decides: it stops if the closing quote
    has a higher logit than the best continuation.

    Args:
        model: Model that provides the logits and decoding.
        token_ids: Token ids so far. It is modified.
        id_to_token: Mapping token id to token string.
        valid_names: Names of the available functions.

    Returns:
        The chosen name, or "" if it is not completed within 200
        tokens.

    Raises:
        ValueError: If no valid token exists at some step.
    """

    max_func_name_tokens = 200
    prompt_length = len(token_ids)
    for _ in range(max_func_name_tokens):
        generated_text = model.decode(token_ids[prompt_length:])
        if (generated_text in valid_names and
                count_matching_prefixes(generated_text,
                                        valid_names) == 1):
            return str(generated_text)

        logits = model.get_logits_from_input_ids(token_ids)
        is_valid = partial(is_valid_prefix, valid_names=valid_names)
        masked_logits = mask_logits(logits, id_to_token,
                                    generated_text, is_valid)
        selected_token_id = select_valid_token(masked_logits)
        if generated_text in valid_names:
            best_quote = float("-inf")
            for token_id, token in id_to_token.items():
                if token.startswith('"') and logits[token_id] > best_quote:
                    best_quote = logits[token_id]
            if best_quote > logits[selected_token_id]:
                return str(generated_text)
        token_ids.append(int(selected_token_id))

    return ""


def _text_before_closing_quote(text: str) -> str:
    """Returns the text before the first unescaped double quote.

    A quote preceded by a backslash is part of the content, so it is
    skipped. If there is no closing quote the whole text is returned.

    Args:
        text: Decoded text of a token.

    Returns:
        The part of text before the closing quote.
    """

    escaped = False
    for i, char in enumerate(text):
        if escaped:
            escaped = False
        elif char == '\\':
            escaped = True
        elif char == '"':
            return text[:i]
    return text


def _generate_string_param(model: Small_LLM_Model, token_ids: list[int],
                           id_to_token: dict[int, str]) -> str | None:
    """Generates the value of a string parameter.

    Appends the opening quote, then at each step only tokens that keep
    the content a valid JSON string is allowed. When the chosen
    token contains the closing quote, only the text before it is kept
    (re-encoded from the decoded token, because raw vocabulary strings
    are not real text) and generation stops. Then the closing quote is
    appended and the content is unescaped with json.loads. At most 200
    tokens are generated, so a longer value is cut there.

    Args:
        model: Model that provides the logits, encoding and decoding.
        token_ids: Token ids so far. It is modified.
        id_to_token: Mapping token id to token string.

    Returns:
        The unescaped string, or None if the content is not a valid
        JSON string.

    Raises:
        ValueError: If no valid token exists at some step.
    """

    max_string_tokens = 200
    _append_tokens(model, token_ids, '"')
    value_text = ""
    value_start = len(token_ids)

    for _ in range(max_string_tokens):
        logits = model.get_logits_from_input_ids(token_ids)
        masked_logits = mask_logits(logits, id_to_token,
                                    value_text, is_valid_string)
        id_token = int(select_valid_token(masked_logits))
        raw_token = id_to_token.get(id_token, "")
        candidate = value_text + raw_token
        state = is_valid_string(candidate)

        if state == 4:
            token_text = model.decode([id_token])
            content_before = _text_before_closing_quote(token_text)
            if content_before:
                _append_tokens(model, token_ids, content_before)
                value_text = model.decode(token_ids[value_start:])
            break

        token_ids.append(id_token)
        value_text = model.decode(token_ids[value_start:])

    _append_tokens(model, token_ids, '"')

    try:
        decoded_val = json.loads(f'"{value_text}"')
        return str(decoded_val)
    except json.JSONDecodeError:
        return None


def _generate_boolean_param(model: Small_LLM_Model, token_ids: list[int],
                            id_to_token: dict[int, str]) -> bool | None:
    """Generates the value of a boolean parameter.

    Only tokens that keep the text as a prefix of "true" or "false"
    are allowed. It stops when the decoded text is one of them. At
    most 20 tokens are generated.

    Args:
        model: Model that provides the logits and decoding.
        token_ids: Token ids so far. It is modified.
        id_to_token: Mapping token id to token string.

    Returns:
        True or False, or None if the text is not complete.

    Raises:
        ValueError: If no valid token exists at some step.
    """

    max_boolean_tokens = 20
    boolean_values = ["true", "false"]
    value_text = ""
    value_start = len(token_ids)
    for _ in range(max_boolean_tokens):
        value_text = model.decode(token_ids[value_start:])
        if (value_text in boolean_values and
                count_matching_prefixes(value_text,
                                        boolean_values) == 1):
            break

        logits = model.get_logits_from_input_ids(token_ids)
        is_valid = partial(is_valid_prefix, valid_names=boolean_values)
        masked_logits = mask_logits(logits, id_to_token, value_text, is_valid)
        id_token = select_valid_token(masked_logits)
        token_ids.append(int(id_token))

    if value_text not in boolean_values:
        return None

    return value_text == "true"


def _generate_number_param(model: Small_LLM_Model, token_ids: list[int],
                           id_to_token: dict[int, str],
                           param_type_name: str) -> int | float | None:
    """Generates the value of a number or integer parameter.

    At each step the token the model prefers decides whether to
    continue: if it keeps the text a valid number it is accepted
    (after masking, which is a safety net), otherwise generation
    stops. Until the first digit exists it never stops: it takes the
    best valid token instead, so the value cannot end as " " or "-".
    The model itself emits the space before the number, which lets it
    choose the token 'Ġ-' for negative numbers. The leading space is
    harmless: int() and float() ignore it. At most 20 tokens are
    generated.

    Args:
        model: Model that provides the logits and decoding.
        token_ids: Token ids so far. It is modified.
        id_to_token: Mapping token id to token string.
        param_type_name: "number" (decimals allowed) or "integer".

    Returns:
        A float for "number", an int for "integer", or None if
        nothing valid was generated.

    Raises:
        ValueError: If no valid token exists at some step.
    """

    max_number_tokens = 20
    value_text = ""
    value_start = len(token_ids)
    allow_decimal = param_type_name == "number"
    for _ in range(max_number_tokens):
        logits = model.get_logits_from_input_ids(token_ids)
        has_digit = False
        for char in value_text:
            if char.isdigit():
                has_digit = True
        id_token_raw = numpy.argmax(logits)
        if int(id_token_raw) not in id_to_token:
            break

        raw_token = id_to_token[int(id_token_raw)]
        raw_candidate = value_text + raw_token

        if is_valid_number_char(raw_candidate, allow_decimal) or not has_digit:
            is_valid = partial(is_valid_number_char,
                               allow_decimal=allow_decimal)
            masked_logits = mask_logits(logits, id_to_token,
                                        value_text, is_valid)
            id_token = select_valid_token(masked_logits)
            token_ids.append(int(id_token))
            value_text = model.decode(token_ids[value_start:])
        else:
            break

    if not value_text:
        return None

    try:
        if allow_decimal:
            return float(value_text)
        else:
            return int(value_text)
    except ValueError:
        return None


def _process_single_test(test: TestPrompt, functions: list[FunctionDefinition],
                         valid_names: list[str], id_to_token: dict[int, str],
                         model: Small_LLM_Model) -> dict[str, Any]:
    """Turns one test prompt into a function call.

    Steps:
        1. A blank prompt returns an ERROR result without using the
           model.
        2. Build the prompt, encode it and force '{"name": "'.
        3. Let the model choose the function name (constrained).
        4. Force '", "parameters": {'.
        5. For each parameter of the chosen function, force its key
           (preceded by ', ' after the first one) and let the model
           generate the value according to its type. For string and
           boolean the key ends with ': '. For number and integer it
           ends with ':' so the model chooses the space itself, which
           makes negative numbers possible.
        6. Force the closing '}'.

    Args:
        test: The request to process.
        functions: Available function definitions.
        valid_names: Names of the available functions.
        id_to_token: Mapping token id to token string.
        model: Model used for generation.

    Returns:
        Dict with keys prompt, name and parameters, or an ERROR entry
        if the function or any value could not be generated.
    """

    if not test.prompt.strip():
        return build_error_result(test.prompt, "prompt is empty or blank")

    prompt = build_prompt(functions, test.prompt)
    ids = model.encode(prompt)
    token_ids: list[int] = ids[0].tolist()

    _append_tokens(model, token_ids, '{"name": "')

    function_name = _generate_function_name(
        model, token_ids, id_to_token, valid_names)

    selected_function = None
    for func in functions:
        if func.name == function_name:
            selected_function = func
            break

    if selected_function is None:
        return build_error_result(test.prompt, f"could not determine a valid "
                                  f"function for prompt: {test.prompt}")

    _append_tokens(model, token_ids, '", "parameters": {')

    parameters_dict: dict[str, str | int | float | bool] = {}

    for index, (param_name, param_type) in (
            enumerate(selected_function.parameters.items())):
        if index > 0:
            _append_tokens(model, token_ids, ", ")
        if param_type.type in ("number", "integer"):
            _append_tokens(model, token_ids, f'"{param_name}":')
        else:
            _append_tokens(model, token_ids, f'"{param_name}": ')

        parsed_value: str | int | float | bool | None = None
        if param_type.type == "string":
            parsed_value = _generate_string_param(model, token_ids,
                                                  id_to_token)
        elif param_type.type == "boolean":
            parsed_value = _generate_boolean_param(model, token_ids,
                                                   id_to_token)
        else:
            parsed_value = _generate_number_param(model, token_ids,
                                                  id_to_token, param_type.type)

        if parsed_value is None:
            return build_error_result(test.prompt, f"could not generate a "
                                      f"valid value for parameter "
                                      f"'{param_name}' in prompt: "
                                      f"{test.prompt}")

        parameters_dict[param_name] = parsed_value

    _append_tokens(model, token_ids, "}")

    result = FunctionCallResult(
        prompt=test.prompt,
        name=function_name,
        parameters=parameters_dict
    )
    return result.model_dump()


def generate_function_calls(vocab: dict[str, int],
                            functions: list[FunctionDefinition],
                            tests: list[TestPrompt],
                            model: Small_LLM_Model) -> list[dict[str, Any]]:
    """Generates one function call for every test prompt.

    The inverted vocabulary and the list of names are computed once.
    Each prompt is processed inside its own try/except, so an
    unexpected error in one prompt gives an ERROR entry for it and
    the rest are still processed.

    Args:
        vocab: Mapping token string to token id.
        functions: Available function definitions.
        tests: Prompts to translate.
        model: Model used for generation.

    Returns:
        One dict per prompt, in the same order as tests.
    """

    results = []
    id_to_token = invert_vocab(vocab)
    valid_names = get_valid_function_names(functions)

    for test in tests:
        try:
            test_result = _process_single_test(test, functions, valid_names,
                                               id_to_token, model)
            results.append(test_result)
        except Exception as e:
            results.append(build_error_result(
                test.prompt, f"unexpected error while processing "
                f"prompt '{test.prompt}': {e}"))
    return results
